import { db } from "./index";
import { recipesTable, type InsertRecipe } from "./schema/recipes";

const recipes: InsertRecipe[] = [
  {
    slug: "lemon-herb-roast-chicken",
    title: "Lemon Herb Roast Chicken",
    description:
      "A whole chicken roasted until the skin shatters, brined in nothing more than salt, lemon, and time. This is the recipe to memorize.",
    category: "Main Course",
    cuisine: "American",
    imageUrl: "/images/chicken.jpg",
    prepMinutes: 15,
    cookMinutes: 75,
    totalMinutes: 90,
    servings: 4,
    dietaryTags: ["Gluten-Free", "High-Protein"],
    cookMethod: "Roasted",
    rating: 4.8,
    reviewCount: 412,
    ingredients: [
      { item: "1 whole chicken (4-5 lb)", note: "patted fully dry" },
      { item: "1 lemon", note: "halved" },
      { item: "4 cloves garlic", note: "smashed" },
      { item: "3 tbsp butter", note: "softened" },
      { item: "2 tbsp fresh thyme", note: null },
      { item: "1 tbsp kosher salt", note: null },
      { item: "1 tsp black pepper", note: null },
    ],
    instructions: [
      { step: 1, text: "Pat the chicken completely dry, inside and out. Dry skin is the whole secret to crackling skin.", timerMinutes: null },
      { step: 2, text: "Season the cavity with salt, then stuff with the lemon halves, garlic, and half the thyme.", timerMinutes: null },
      { step: 3, text: "Rub the softened butter under and over the skin, then season generously with remaining salt, pepper, and thyme.", timerMinutes: null },
      { step: 4, text: "Truss the legs and let the chicken sit at room temperature.", timerMinutes: 30 },
      { step: 5, text: "Roast at 425°F, breast-side up, until the skin is deep golden and a thermometer in the thigh reads 165°F.", timerMinutes: 75 },
      { step: 6, text: "Rest before carving so the juices redistribute.", timerMinutes: 10 },
    ],
    caloriesPerServing: 520,
    proteinG: 46,
    carbsG: 2,
    fatG: 34,
  },
  {
    slug: "brown-butter-chocolate-chip-cookies",
    title: "Brown Butter Chocolate Chip Cookies",
    description:
      "Nutty brown butter and two kinds of sugar push these past ordinary into the territory of a genuinely great cookie.",
    category: "Dessert",
    cuisine: "American",
    imageUrl: "/images/cookies.jpg",
    prepMinutes: 20,
    cookMinutes: 12,
    totalMinutes: 32,
    servings: 18,
    dietaryTags: ["Vegetarian"],
    cookMethod: "Baked",
    rating: 4.9,
    reviewCount: 588,
    ingredients: [
      { item: "1 cup butter", note: "browned and cooled" },
      { item: "1 cup brown sugar", note: null },
      { item: "1/2 cup granulated sugar", note: null },
      { item: "2 eggs", note: null },
      { item: "2 1/4 cups flour", note: null },
      { item: "1 tsp baking soda", note: null },
      { item: "1 tsp salt", note: null },
      { item: "2 cups chocolate chips", note: "mix of dark and milk" },
    ],
    instructions: [
      { step: 1, text: "Brown the butter in a light-colored pan until it smells nutty and the solids turn amber. Cool slightly.", timerMinutes: 8 },
      { step: 2, text: "Whisk the browned butter with both sugars until glossy.", timerMinutes: null },
      { step: 3, text: "Beat in the eggs one at a time.", timerMinutes: null },
      { step: 4, text: "Fold in the flour, baking soda, and salt until just combined, then fold in chocolate chips.", timerMinutes: null },
      { step: 5, text: "Chill the dough so the flavor deepens and the cookies hold their shape.", timerMinutes: 30 },
      { step: 6, text: "Scoop and bake at 350°F until the edges are set but centers still look slightly underdone.", timerMinutes: 12 },
    ],
    caloriesPerServing: 240,
    proteinG: 3,
    carbsG: 29,
    fatG: 13,
  },
  {
    slug: "cast-iron-smash-burgers",
    title: "Cast Iron Smash Burgers",
    description:
      "Thin, lacy-edged patties smashed hard into a screaming-hot pan for maximum crust. Diner-quality, made at home.",
    category: "Main Course",
    cuisine: "American",
    imageUrl: "/images/burger.jpg",
    prepMinutes: 10,
    cookMinutes: 8,
    totalMinutes: 18,
    servings: 4,
    dietaryTags: ["High-Protein"],
    cookMethod: "Pan-Seared",
    rating: 4.7,
    reviewCount: 301,
    ingredients: [
      { item: "1 lb ground beef (80/20)", note: "loosely formed into 4 balls" },
      { item: "4 slices American cheese", note: null },
      { item: "4 burger buns", note: "toasted" },
      { item: "2 tbsp mayonnaise", note: null },
      { item: "1 tbsp yellow mustard", note: null },
      { item: "1/2 cup diced onion", note: null },
      { item: "Salt and pepper", note: "to taste" },
    ],
    instructions: [
      { step: 1, text: "Heat a cast iron skillet until it's smoking hot.", timerMinutes: null },
      { step: 2, text: "Place a beef ball on the skillet, top with diced onion, and smash flat immediately with a spatula.", timerMinutes: null },
      { step: 3, text: "Season with salt and pepper, sear until deeply crusted.", timerMinutes: 3 },
      { step: 4, text: "Flip, add cheese, and cook until melted.", timerMinutes: 2 },
      { step: 5, text: "Build the burger on a toasted bun with mayo and mustard.", timerMinutes: null },
    ],
    caloriesPerServing: 610,
    proteinG: 32,
    carbsG: 30,
    fatG: 38,
  },
  {
    slug: "coconut-curry-noodle-soup",
    title: "Coconut Curry Noodle Soup",
    description:
      "A fast weeknight soup built on canned coconut milk and red curry paste, finished with lime and a chili-oil swirl.",
    category: "Soup",
    cuisine: "Thai-Inspired",
    imageUrl: "/images/noodlesoup.jpg",
    prepMinutes: 10,
    cookMinutes: 20,
    totalMinutes: 30,
    servings: 4,
    dietaryTags: ["Vegetarian", "Gluten-Free"],
    cookMethod: "Simmered",
    rating: 4.6,
    reviewCount: 219,
    ingredients: [
      { item: "2 tbsp red curry paste", note: null },
      { item: "2 cans coconut milk", note: null },
      { item: "3 cups vegetable stock", note: null },
      { item: "8 oz rice noodles", note: null },
      { item: "2 cups shiitake mushrooms", note: "sliced" },
      { item: "2 cups baby bok choy", note: null },
      { item: "1 lime", note: "juiced" },
      { item: "Chili oil", note: "for serving" },
    ],
    instructions: [
      { step: 1, text: "Bloom the curry paste in a splash of coconut milk over medium heat until fragrant.", timerMinutes: 2 },
      { step: 2, text: "Add the remaining coconut milk and stock, bring to a simmer.", timerMinutes: 5 },
      { step: 3, text: "Add mushrooms and simmer until tender.", timerMinutes: 8 },
      { step: 4, text: "Add noodles and bok choy, cook until noodles are just tender.", timerMinutes: 5 },
      { step: 5, text: "Finish with lime juice and a swirl of chili oil.", timerMinutes: null },
    ],
    caloriesPerServing: 430,
    proteinG: 10,
    carbsG: 48,
    fatG: 22,
  },
  {
    slug: "soft-scrambled-eggs-with-chive-creme-fraiche",
    title: "Soft Scrambled Eggs with Chive Crème Fraîche",
    description:
      "Low and slow scrambled eggs, pulled off the heat while still glossy, finished with cold crème fraîche so they never overcook.",
    category: "Breakfast",
    cuisine: "French-Inspired",
    imageUrl: "/images/eggs.jpg",
    prepMinutes: 5,
    cookMinutes: 8,
    totalMinutes: 13,
    servings: 2,
    dietaryTags: ["Vegetarian", "Gluten-Free", "High-Protein"],
    cookMethod: "Stovetop",
    rating: 4.7,
    reviewCount: 156,
    ingredients: [
      { item: "5 eggs", note: null },
      { item: "2 tbsp butter", note: null },
      { item: "3 tbsp crème fraîche", note: "cold, plus more to serve" },
      { item: "2 tbsp chives", note: "finely chopped" },
      { item: "Flaky salt", note: null },
      { item: "2 slices sourdough toast", note: null },
    ],
    instructions: [
      { step: 1, text: "Whisk eggs with a pinch of salt until fully combined.", timerMinutes: null },
      { step: 2, text: "Melt butter in a nonstick pan over low heat, add eggs.", timerMinutes: null },
      { step: 3, text: "Stir constantly with a spatula, pulling curds from the edges, removing from heat while still slightly wet.", timerMinutes: 6 },
      { step: 4, text: "Off heat, fold in cold crème fraîche until glossy and just set.", timerMinutes: null },
      { step: 5, text: "Top with chives and flaky salt, serve over toast.", timerMinutes: null },
    ],
    caloriesPerServing: 380,
    proteinG: 20,
    carbsG: 14,
    fatG: 27,
  },
  {
    slug: "shaved-fennel-and-blood-orange-salad",
    title: "Shaved Fennel and Blood Orange Salad",
    description:
      "Crisp fennel, sweet-tart blood orange, and briny olives — a salad built entirely on contrast.",
    category: "Salad",
    cuisine: "Italian-Inspired",
    imageUrl: "/images/salad.jpg",
    prepMinutes: 15,
    cookMinutes: 0,
    totalMinutes: 15,
    servings: 4,
    dietaryTags: ["Vegan", "Gluten-Free"],
    cookMethod: "No-Cook",
    rating: 4.5,
    reviewCount: 98,
    ingredients: [
      { item: "2 bulbs fennel", note: "shaved thin" },
      { item: "3 blood oranges", note: "segmented" },
      { item: "1/3 cup Castelvetrano olives", note: "pitted, halved" },
      { item: "2 tbsp olive oil", note: null },
      { item: "1 tbsp red wine vinegar", note: null },
      { item: "Flaky salt and pepper", note: null },
    ],
    instructions: [
      { step: 1, text: "Shave the fennel as thin as possible on a mandoline, reserve the fronds.", timerMinutes: null },
      { step: 2, text: "Segment the blood oranges over a bowl to catch the juice.", timerMinutes: null },
      { step: 3, text: "Toss fennel, orange segments, and olives with olive oil, vinegar, and reserved orange juice.", timerMinutes: null },
      { step: 4, text: "Season with salt and pepper, top with fennel fronds.", timerMinutes: null },
    ],
    caloriesPerServing: 140,
    proteinG: 2,
    carbsG: 18,
    fatG: 8,
  },
  {
    slug: "milk-bread-shokupan",
    title: "Milk Bread (Shokupan)",
    description:
      "An enriched Japanese loaf made pillowy-soft with a cooked flour-and-milk paste called tangzhong.",
    category: "Bread",
    cuisine: "Japanese",
    imageUrl: "/images/bread.jpg",
    prepMinutes: 40,
    cookMinutes: 30,
    totalMinutes: 180,
    servings: 12,
    dietaryTags: ["Vegetarian"],
    cookMethod: "Baked",
    rating: 4.8,
    reviewCount: 174,
    ingredients: [
      { item: "1/3 cup flour", note: "for tangzhong" },
      { item: "1/2 cup milk", note: "for tangzhong" },
      { item: "3 cups bread flour", note: null },
      { item: "1/4 cup sugar", note: null },
      { item: "2 1/4 tsp instant yeast", note: null },
      { item: "1 egg", note: null },
      { item: "1/2 cup milk", note: "warm" },
      { item: "4 tbsp butter", note: "softened" },
      { item: "1 tsp salt", note: null },
    ],
    instructions: [
      { step: 1, text: "Cook the tangzhong: whisk flour and milk over low heat until it thickens into a paste. Cool.", timerMinutes: 5 },
      { step: 2, text: "Combine tangzhong, bread flour, sugar, yeast, egg, and warm milk. Mix into a shaggy dough.", timerMinutes: null },
      { step: 3, text: "Knead in butter and salt until the dough is smooth and elastic.", timerMinutes: 12 },
      { step: 4, text: "Let rise until doubled.", timerMinutes: 60 },
      { step: 5, text: "Shape into the loaf pan and proof again.", timerMinutes: 45 },
      { step: 6, text: "Bake at 350°F until deeply golden and it sounds hollow when tapped.", timerMinutes: 30 },
    ],
    caloriesPerServing: 190,
    proteinG: 5,
    carbsG: 30,
    fatG: 5,
  },
  {
    slug: "saffron-risotto-with-crispy-prosciutto",
    title: "Saffron Risotto with Crispy Prosciutto",
    description:
      "Slow-stirred risotto Milanese-style, gilded with saffron and topped with shattering-crisp prosciutto.",
    category: "Main Course",
    cuisine: "Italian",
    imageUrl: "/images/risotto.jpg",
    prepMinutes: 10,
    cookMinutes: 35,
    totalMinutes: 45,
    servings: 4,
    dietaryTags: ["Gluten-Free"],
    cookMethod: "Stovetop",
    rating: 4.7,
    reviewCount: 143,
    ingredients: [
      { item: "1 1/2 cups arborio rice", note: null },
      { item: "5 cups chicken stock", note: "kept warm" },
      { item: "1/2 tsp saffron threads", note: "steeped in warm stock" },
      { item: "1/2 cup white wine", note: null },
      { item: "1 small onion", note: "finely diced" },
      { item: "1/2 cup parmesan", note: "grated" },
      { item: "4 slices prosciutto", note: null },
      { item: "3 tbsp butter", note: null },
    ],
    instructions: [
      { step: 1, text: "Crisp the prosciutto in a dry pan until brittle, set aside.", timerMinutes: 5 },
      { step: 2, text: "Sauté onion in butter until translucent, add rice and toast for a minute.", timerMinutes: 3 },
      { step: 3, text: "Deglaze with white wine, cook until absorbed.", timerMinutes: 2 },
      { step: 4, text: "Add saffron stock one ladle at a time, stirring constantly, waiting for each addition to absorb.", timerMinutes: 25 },
      { step: 5, text: "Off heat, stir in parmesan and remaining butter until glossy.", timerMinutes: null },
      { step: 6, text: "Serve topped with crispy prosciutto shards.", timerMinutes: null },
    ],
    caloriesPerServing: 480,
    proteinG: 16,
    carbsG: 58,
    fatG: 18,
  },
  {
    slug: "cardamom-rose-panna-cotta",
    title: "Cardamom Rose Panna Cotta",
    description:
      "A wobbly, barely-set cream dessert perfumed with cardamom and a whisper of rosewater.",
    category: "Dessert",
    cuisine: "Fusion",
    imageUrl: "/images/pannacotta.jpg",
    prepMinutes: 15,
    cookMinutes: 5,
    totalMinutes: 260,
    servings: 6,
    dietaryTags: ["Vegetarian", "Gluten-Free"],
    cookMethod: "Chilled",
    rating: 4.6,
    reviewCount: 87,
    ingredients: [
      { item: "2 cups heavy cream", note: null },
      { item: "1/2 cup whole milk", note: null },
      { item: "1/3 cup sugar", note: null },
      { item: "1 tsp ground cardamom", note: null },
      { item: "1 tsp rosewater", note: null },
      { item: "2 1/4 tsp powdered gelatin", note: "bloomed in cold water" },
      { item: "Dried rose petals", note: "to garnish" },
    ],
    instructions: [
      { step: 1, text: "Bloom the gelatin in a few tablespoons of cold water.", timerMinutes: 5 },
      { step: 2, text: "Heat cream, milk, sugar, and cardamom until just simmering, do not boil.", timerMinutes: 5 },
      { step: 3, text: "Remove from heat, whisk in bloomed gelatin and rosewater until fully dissolved.", timerMinutes: null },
      { step: 4, text: "Strain into serving glasses and chill until fully set.", timerMinutes: 240 },
      { step: 5, text: "Garnish with dried rose petals before serving.", timerMinutes: null },
    ],
    caloriesPerServing: 310,
    proteinG: 4,
    carbsG: 16,
    fatG: 25,
  },
  {
    slug: "grilled-lamb-kofta-with-tzatziki",
    title: "Grilled Lamb Kofta with Tzatziki",
    description:
      "Spiced ground lamb skewers charred hard over direct heat, cooled down with a cucumber-yogurt tzatziki.",
    category: "Appetizer",
    cuisine: "Mediterranean",
    imageUrl: "/images/kofta.jpg",
    prepMinutes: 20,
    cookMinutes: 10,
    totalMinutes: 30,
    servings: 4,
    dietaryTags: ["High-Protein", "Gluten-Free"],
    cookMethod: "Grilled",
    rating: 4.7,
    reviewCount: 132,
    ingredients: [
      { item: "1 lb ground lamb", note: null },
      { item: "1 small onion", note: "grated and squeezed dry" },
      { item: "2 cloves garlic", note: "minced" },
      { item: "1 tsp cumin", note: null },
      { item: "1 tsp smoked paprika", note: null },
      { item: "1/4 cup parsley", note: "chopped" },
      { item: "1 cup Greek yogurt", note: "for tzatziki" },
      { item: "1/2 cucumber", note: "grated and squeezed dry" },
      { item: "1 clove garlic", note: "for tzatziki, minced" },
    ],
    instructions: [
      { step: 1, text: "Mix lamb, onion, garlic, cumin, paprika, parsley, and salt until just combined.", timerMinutes: null },
      { step: 2, text: "Shape around skewers into oblong logs, chill briefly to firm up.", timerMinutes: 15 },
      { step: 3, text: "Stir together yogurt, cucumber, and garlic for the tzatziki, season with salt.", timerMinutes: null },
      { step: 4, text: "Grill kofta over high heat, turning until charred on all sides and cooked through.", timerMinutes: 10 },
      { step: 5, text: "Serve hot with tzatziki alongside.", timerMinutes: null },
    ],
    caloriesPerServing: 340,
    proteinG: 26,
    carbsG: 6,
    fatG: 24,
  },
];

async function seed() {
  for (const recipe of recipes) {
    await db.insert(recipesTable).values(recipe).onConflictDoNothing({
      target: recipesTable.slug,
    });
  }
  console.log(`Seeded ${recipes.length} recipes.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
